services:
  - type: web
    name: soas-api
    runtime: node
    rootDir: server
    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://fauz-scholarship-alert-1-ghxp.onrender.com
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_REPLY_TO
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMS_BASE_URL
        sync: false
      - key: SMS_API_KEY
        sync: false
      - key: SMS_SENDER_ID
        sync: false
